server:
  port: 8088

spring:
  profile:
    active: local
  thymeleaf:
    check-template-location: true
    prefix: classpath:/templates/
    suffix: .html
    cache: false
  mvc:
    static-path-pattern: /static/**
    hidden-method:
      filter:
        enabled: true
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://10.41.1.198:3306/team35
    username: team35
    password: bobo35
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 100MB
      location: C://upload
  messages:
    basename: messages
    encoding: UTF-8
  mail:
    host: smtp.naver.com
    port: 465
    username: juncheol08@naver.com
    password: cjswo0825!
    properties:
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true
      mail.smtp.ssl.trust: smtp.naver.com
      mail.smtp.starttls.enable: true

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.tsherpa.team35.entity
  mapper-locations: mappers/**/*.xml

logging:
  config: classpath:logback.xml
  level:
    org:
      springframework: info

itemImgLocation: C:/team35/item
uploadPath: file:///C:/team35

